export interface SpeciesDTO {
    'base_happiness': number, 
    'capture_rate': number, 
    'color': {name: string, url: string}, 
    'egg_groups': Array<{}>, 
    'evolution_chain': {}, 
    'evolves_from_species': {name: string; url: string}, 
    'flavor_text_entries': Array<{}>, 
    'form_descriptions': Array<{}>, 
    'forms_switchable': boolean, 
    'gender_rate': number, 
    'genera': Array<{}>, 
    'generation': {}, 
    'growth_rate': {name: string; url: string}, 
    'habitat': string, 
    'has_gender_differences': boolean, 
    'hatch_counter': number, 
    'id': number, 
    'is_baby': boolean, 
    'is_legendary': boolean, 
    'is_mythical': boolean, 
    'name': string, 
    'names': Array<{}>, 
    'order': number, 
    'pal_park_encounters': Array<{}>,
    'pokedex_numbers': Array<{}>, 
    'shape': {}, 
    'varieties': Array<{}>
}